---
user:
  name: ##YOUR-FULL-NAME##
  editor: #"vim -O"

path: "~"
output_path: "."
list:
  colors:    true
  verbose:   true
  sort:      index
  gitstatus: true

  extra_details: #[OurBad, Caterers] # see asciii list --computed for all options

## CAREFUL HERE -BREAK- everything below here will not be copied over
dirs:
  storage: ".asciii_projects"
  working: working
  archive: archive
  templates: templates

template: default # default template

extensions:
  project_file: yml
  project_template: tyml
  output_file: tex
  output_template: tex.hbs

document_export:
  convert_tool: pdflatex
  output_extension: pdf
  trash_extensions: [aux,log]
  default_template: export

#log_file: ~/.ascii_log # unimplemented
#calendar_file: invoicer.ics #unimplemented

defaults:
  tax: 0.19
  canceled: false
  salary: 8.0
  lang: de

currency: "€"

gender_matches:
  mr: male
  ms: female
  mrs: female
  herr: male
  frau: female
  professor: male
  professorin: female

lang_addressing:
  de:
    male: Sehr geehrter
    female: Sehr geehrte
  en:
    male: Dear
    female: Dear
...
